name: build-ai-news

on:
  schedule:
    - cron: "0 21 * * *"  # JST 6:00
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install feedparser jinja2
      - run: python scripts/build_news.py
      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "auto: update news $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "no changes"
          fi
